service: my-lambda-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
