name: AWS Lambda Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Configure AWS credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          role-to-assume: arn:aws:iam::750344256621:oidc-provider/token.actions.githubusercontent.com
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: npx serverless deploy

